import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../../components/Header";
import Banner from "../../components/Banner";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Ethentivize</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <>
        <Banner />
      </>
    </div>
  );
};

export default Home;
